### ISSUE TITLE
TypeError encountered while closing GitHub milestones when the "Due Date" is not defined

### ISSUE THREAD

**Issue by mpawlow** [mpawlow/github-milestone-generator#3]
```
[2019-09-04 18:12:47,183] [INFO ] [__main__] Connecting to GitHub API v3: https://github.ibm.com/api/v3...
[2019-09-04 18:12:47,184] [INFO ] [__main__] Successfully connected to GitHub API v3: https://github.ibm.com/api/v3.
[2019-09-04 18:12:47,184] [INFO ] [__main__] Retrieving GitHub repository: dap/dap-planning...
[2019-09-04 18:12:47,509] [INFO ] [__main__] Successfully retrieved GitHub repository: dap/dap-planning.
[2019-09-04 18:12:47,509] [INFO ] [__main__] Retrieving all open GitHub milestones...
[2019-09-04 18:12:47,572] [INFO ] [__main__] Successfully retrieved all open GitHub milestones: 18.
[2019-09-04 18:12:47,572] [INFO ] [__main__] Closing overdue GitHub milestones (2019-09-04 18:12:47.572917)...
Traceback (most recent call last):
  File "index.py", line 738, in <module>
    _main()
  File "index.py", line 721, in _main
    milestones=open_milestones)
  File "index.py", line 465, in _close_overdue_github_milestones
    if current_time > milestone.due_on:
TypeError: '>' not supported between instances of 'datetime.datetime' and 'NoneType'

```

**Comment by mpawlow** [comment]
Fixed.
