### ISSUE TITLE
Exception encountered trying to close milestones: TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by mpawlow** [mpawlow/github-milestone-generator#7]
## Exception

```
$ python index.py -c -r dap/dap-planning
[2019-10-03 18:50:59,222] [INFO ] [__main__] [-- GITHUB MILESTONE GENERATOR ------------------------------------------------
[2019-10-03 18:50:59,222] [INFO ] [__main__] Parsed Command-line Arguments:
GitHub API Domain: github.ibm.com.
GitHub Repository: dap/dap-planning.
New Milestone Name: None.
New Milestone Due Date: None.
Close Milestones: True.
Logging Level: INFO.
Traceback (most recent call last):
  File "index.py", line 744, in <module>
    _main()
  File "index.py", line 693, in _main
    date=args.milestone_due_date)
  File "index.py", line 244, in _validate_milestone_due_date
    status = _validate_iso_8601_date(date)
  File "index.py", line 259, in _validate_iso_8601_date
    match = re.fullmatch(ISO_8601_DATE_REGEX, date)
  File "C:\Users\MikePawlowski\AppData\Local\Programs\Python\Python37\lib\re.py", line 178, in fullmatch
    return _compile(pattern, flags).fullmatch(string)
TypeError: expected string or bytes-like object
(github-milestone-generator)

```

**Comment by mpawlow** [comment]
Fixed.
